name: Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: alpine
    container: pretendonetwork/yo-kai-watch-blasters:sha-90c3511

    steps:
      - uses: actions/checkout@v4
      - name: ls
        run: ls "/home/go/app/"

      
    
      #- name: database
      #  run: sudo apt install postgresql -y && sh ./postgres.sh
        
      #- name: ip address
      #  run: 
