name: Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: golang:latest
    steps:
      - uses: actions/checkout@v4
      
      - name: make
        run: make
        
      - name: ls
        run: ls "/home/go/app/"
      
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: ./
        
      #- name: database
      #  run: sudo apt install postgresql -y && sh ./postgres.sh
 
